#!/usr/bin/env bash
# Generate the amalgamation: mizu.c + mizu.h + mizu_ext.h, for consumers
# that integrate the sources with their own build system.
#
# Usage: tools/amalgamate.sh [outdir]   (default: the repo root)
#
# mizu.h / mizu_ext.h are the verbatim public and binding-author headers
# plus a stamp/license banner; mizu.c is the internal header plus every
# core TU with its local includes stripped (src/ext.c excluded — its
# exported dual-form symbols would redefine the static inlines mizu_ext.h
# already gives the single TU; C consumers get the inlines, FFI
# consumers use the shared library). All banners carry the version/SHA
# stamp and the license notices, so the trio ships self-contained (bare
# release assets). Idempotent.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT}"

mkdir -p "$OUT"

# Version from the header's MIZU_VERSION_* macros (the single source of
# truth); the SHA stamps provenance (-dirty on uncommitted changes,
# unknown outside a git checkout). Both banners carry the same stamp
# line — the consumer's skew guard when fetching the bare files.
VERSION=$(awk '/^#define MIZU_VERSION_(MAJOR|MINOR|PATCH)/ { printf "%s%s", sep, $3; sep = "." }' "$ROOT/include/mizu.h")
[ -n "$VERSION" ] || { echo "amalgamate.sh: could not parse MIZU_VERSION_* from include/mizu.h" >&2; exit 1; }
if SHA=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null); then
  git -C "$ROOT" diff --quiet HEAD 2>/dev/null || SHA="$SHA-dirty"
else
  SHA=unknown
fi
STAMP="libmizu $VERSION ($SHA)"

{
  echo "/* mizu.c — the libmizu amalgamation, generated by tools/amalgamate.sh;"
  echo "   do not edit. Sources: the src/ tree at this repo state."
  echo "   Version: $STAMP"
  echo "   (mizu.h and mizu_ext.h alongside must carry the same Version stamp.)"
  echo
  echo "   Copyright (c) 2026 libmizu authors. SPDX-License-Identifier: MIT."
  echo "   The RNG jump kernel below derives from the RngStreams package by"
  echo "   Pierre L'Ecuyer (Apache License 2.0) — its attribution notice is"
  echo "   retained inline; full texts: LICENSE and LICENSE.note at"
  echo "   https://github.com/shikokuchuo/libmizu."
  echo
  echo "   mizu.h (alongside) is the public API; mizu_ext.h the binding-author"
  echo "   tier. No defines needed: MIZU_API defaults to empty (define"
  echo "   MIZU_SHARED for a shared-library build). */"
  echo
  echo '/* _GNU_SOURCE: glibc hides O_CLOEXEC, MAP_POPULATE, pidfd_open, ...'
  echo '   under strict -std=c11; define before any system header (mizu.h'
  echo '   pulls in features.h). */'
  echo '#if defined(__linux__) && !defined(_GNU_SOURCE)'
  echo '#  define _GNU_SOURCE'
  echo '#endif'
  echo
  echo '#include "mizu.h"'
  echo '#include "mizu_ext.h"'
  echo
  # internal.h, minus its guard and its includes (mizu.h + mizu_ext.h are
  # above; the system includes are repeated harmlessly per-file below).
  sed -e '/#ifndef MIZU_INTERNAL_H/d' \
      -e '/#define MIZU_INTERNAL_H/d' \
      -e '/#include "mizu.h"/d' \
      -e '/#include "mizu_ext.h"/d' \
      -e '/#endif \/\* MIZU_INTERNAL_H \*\//d' \
      "$ROOT/src/internal.h"
  # src/ext.c is excluded: its exported dual-form symbols would redefine
  # the static inlines mizu_ext.h already gave this single TU.
  for f in "$ROOT"/src/*.c; do
    [ "$f" = "$ROOT/src/ext.c" ] && continue
    echo
    echo "/* ---- src/$(basename "$f") ---- */"
    echo
    sed -e '/#include "internal.h"/d' \
        -e '/#include "mizu.h"/d' \
        -e '/#include "mizu_ext.h"/d' \
        "$f"
  done
} > "$OUT/mizu.c"

# mizu.h / mizu_ext.h are include/ verbatim under the banner.
for h in mizu.h mizu_ext.h; do
  if [ "$h" = mizu.h ]; then desc="the libmizu public API"; else desc="the libmizu binding-author API (the unstable tier)"; fi
  {
    echo "/* $h — $desc, amalgamated copy generated by"
    echo "   tools/amalgamate.sh; do not edit."
    echo "   Version: $STAMP"
    echo "   (mizu.c alongside must carry the same Version stamp.)"
    echo
    echo "   Copyright (c) 2026 libmizu authors. SPDX-License-Identifier: MIT."
    echo "   The RNG jump kernel in mizu.c derives from the RngStreams package"
    echo "   by Pierre L'Ecuyer (Apache License 2.0) — attribution and license"
    echo "   texts: LICENSE and LICENSE.note at"
    echo "   https://github.com/shikokuchuo/libmizu."
    echo
    echo "   The amalgamation links statically into the consumer's module:"
    echo "   MIZU_API defaults to empty (define MIZU_SHARED to override). */"
    echo
    cat "$ROOT/include/$h"
  } > "$OUT/$h"
done

echo "wrote $OUT/mizu.c, $OUT/mizu.h and $OUT/mizu_ext.h"
