#!/usr/bin/env bash
# Generate the amalgamation: rei.c + rei.h, for consumers that integrate
# the sources with their own build system.
#
# Usage: tools/amalgamate.sh [outdir]   (default: the repo root)
#
# rei.h is the verbatim public header plus a stamp/license banner; rei.c
# is the internal header plus every core TU with its local includes
# stripped. Both banners carry the version/SHA stamp and the license
# notices, so the pair ships self-contained (bare release assets).
# Idempotent.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT}"

mkdir -p "$OUT"

# Version from the header's REI_VERSION_* macros (the single source of
# truth); the SHA stamps provenance (-dirty on uncommitted changes,
# unknown outside a git checkout). Both banners carry the same stamp
# line — the consumer's skew guard when fetching the bare files.
VERSION=$(awk '/^#define REI_VERSION_(MAJOR|MINOR|PATCH)/ { printf "%s%s", sep, $3; sep = "." }' "$ROOT/include/rei.h")
[ -n "$VERSION" ] || { echo "amalgamate.sh: could not parse REI_VERSION_* from include/rei.h" >&2; exit 1; }
if SHA=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null); then
  git -C "$ROOT" diff --quiet HEAD 2>/dev/null || SHA="$SHA-dirty"
else
  SHA=unknown
fi
STAMP="librei $VERSION ($SHA)"

{
  echo "/* rei.c — the librei amalgamation, generated by tools/amalgamate.sh;"
  echo "   do not edit. Sources: the src/ tree at this repo state."
  echo "   Version: $STAMP"
  echo "   (rei.h alongside must carry the same Version stamp.)"
  echo
  echo "   Copyright (c) 2026 librei authors. SPDX-License-Identifier: MIT."
  echo "   The RNG jump kernel below derives from the RngStreams package by"
  echo "   Pierre L'Ecuyer (Apache License 2.0) — its attribution notice is"
  echo "   retained inline; full texts: LICENSE and LICENSE.note at"
  echo "   https://github.com/shikokuchuo/librei."
  echo
  echo "   rei.h (alongside) is the public API. No defines needed:"
  echo "   REI_API defaults to empty (define REI_SHARED for a"
  echo "   shared-library build). */"
  echo
  echo '/* _GNU_SOURCE: glibc hides O_CLOEXEC, MAP_POPULATE, pidfd_open, ...'
  echo '   under strict -std=c11; define before any system header (rei.h'
  echo '   pulls in features.h). */'
  echo '#if defined(__linux__) && !defined(_GNU_SOURCE)'
  echo '#  define _GNU_SOURCE'
  echo '#endif'
  echo
  echo '#include "rei.h"'
  echo
  # internal.h, minus its guard and its includes (rei.h is above; the
  # system includes are repeated harmlessly per-file below).
  sed -e '/#ifndef REI_INTERNAL_H/d' \
      -e '/#define REI_INTERNAL_H/d' \
      -e '/#include "rei.h"/d' \
      -e '/#endif \/\* REI_INTERNAL_H \*\//d' \
      "$ROOT/src/internal.h"
  for f in "$ROOT"/src/*.c; do
    echo
    echo "/* ---- src/$(basename "$f") ---- */"
    echo
    sed -e '/#include "internal.h"/d' \
        -e '/#include "rei.h"/d' \
        "$f"
  done
} > "$OUT/rei.c"

# rei.h is include/rei.h verbatim under the banner.
{
  echo "/* rei.h — the librei public API, amalgamated copy generated by"
  echo "   tools/amalgamate.sh; do not edit."
  echo "   Version: $STAMP"
  echo "   (rei.c alongside must carry the same Version stamp.)"
  echo
  echo "   Copyright (c) 2026 librei authors. SPDX-License-Identifier: MIT."
  echo "   The RNG jump kernel in rei.c derives from the RngStreams package"
  echo "   by Pierre L'Ecuyer (Apache License 2.0) — attribution and license"
  echo "   texts: LICENSE and LICENSE.note at"
  echo "   https://github.com/shikokuchuo/librei."
  echo
  echo "   The amalgamation links statically into the consumer's module:"
  echo "   REI_API defaults to empty (define REI_SHARED to override). */"
  echo
  cat "$ROOT/include/rei.h"
} > "$OUT/rei.h"

echo "wrote $OUT/rei.c and $OUT/rei.h"
